table Product
	lineageTag: 8513e72a-3663-47bd-9f54-e302e4913e2d

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 3f7e9972-3b6f-4bc5-9e2b-9073cb081fce
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: c7fe2268-60bc-4135-be9a-862a6b8b5e5c
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: fbfee81a-73d3-43e9-9736-772c40c43550
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 34d693dc-7e5d-492d-a518-6a1951743716
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column ManufacturerID
		dataType: int64
		formatString: 0
		lineageTag: 967c1f46-6329-4dea-8ae7-6b60f5c66caa
		summarizeBy: none
		sourceColumn: ManufacturerID

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		lineageTag: ecc37244-2562-4dea-8d4a-283e34d47e73
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

	column 'Unit Cost'
		dataType: double
		lineageTag: 9de483d2-adbc-44f2-a9b0-03f46211dc3f
		summarizeBy: none
		sourceColumn: Unit Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Price'
		dataType: double
		lineageTag: ced6bfb4-5dd7-4e01-8454-7c4f254dbf50
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\datapot-fabric-agent-demo\Dataset\Data lab & assignment\VanArsdel_Actuals.xlsx"), null, true),
				    Product_Sheet = Source{[Item="Product",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Product_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductID", Int64.Type}, {"Product", type text}, {"Category", type text}, {"Segment", type text}, {"ManufacturerID", Int64.Type}, {"Manufacturer", type text}, {"Unit Cost", type number}, {"Unit Price", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

